dad_short_reads_R1: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/dad/HG003_HiSeq30x_subsampled_R1.fastq.gz"
dad_short_reads_R2: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/dad/HG003_HiSeq30x_subsampled_R2.fastq.gz"

mom_short_reads_R1: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/mom/HG004_HiSeq30x_subsampled_R1.fastq.gz"
mom_short_reads_R2: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/mom/HG004_HiSeq30x_subsampled_R2.fastq.gz"

child_short_reads_R1: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/son/short/HG002_HiSeq30x_subsampled_R1.fastq.gz"
child_short_reads_R2: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/son/short/HG002_HiSeq30x_subsampled_R2.fastq.gz"

child_long_reads: "/mnt/beegfs/labs/DiGenomaLab/rfhap/latest_dami/latest_HG00_dataset/HG002/son/standar_ont/sup/PAW71238/HG002_standar_ont_sup_PAW71238.fastq.gz"

hap_mom_ids: "/mnt/beegfs/labs/DiGenomaLab/rfhap/analysis_bayesian/chr_1/results_0.1/A.csv"
hap_dad_ids: "/mnt/beegfs/labs/DiGenomaLab/rfhap/analysis_bayesian/chr_1/results_0.1/B.csv"
hap_unknown_ids: "/mnt/beegfs/labs/DiGenomaLab/rfhap/analysis_bayesian/chr_1/results_0.1/U.csv"
